title: "MockCrypto"
description: "Мобильное приложение для отслеживания курсов криптовалюты и демо трейдинга"

markdown: kramdown
remote_theme: jekyll/minima@master

plugins:
  - jekyll-remote-theme

minima:
  skin: solarized
  date_format: "%b %-d, %Y"
