name: Android CI (Main Branch)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  release:
    types: [published]

permissions:
  contents: write

jobs:
  test:
    name: Run All Tests
    runs-on: ubuntu-latest
    if: github.event_name != 'release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew test --no-daemon

      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedCheck --no-daemon

  build:
    name: Build Release APK
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name != 'release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug --no-daemon  # TODO: change to assembleRelease. Now debug because you can't run release app on your phone without signing it

      - name: Get short SHA
        id: short_sha
        run: echo "SHA=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT
        
      - name: Rename APK with SHA
        run: |
          mkdir -p ./artifacts
          cp app/build/outputs/apk/debug/app-debug.apk ./artifacts/app-debug-${{ steps.short_sha.outputs.SHA }}.apk
        
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned-${{ steps.short_sha.outputs.SHA }}
          path: artifacts/app-debug-${{ steps.short_sha.outputs.SHA }}.apk

  attach-to-release:
    name: Attach APK to Release
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Get short SHA
        id: short_sha
        run: echo "SHA=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Download APK from artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: main_workflow.yml
          name: app-release-unsigned-${{ steps.short_sha.outputs.SHA }}
          path: artifacts

      - name: Attach APK and Commit to Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/app-debug-${{ steps.short_sha.outputs.SHA }}.apk
          token: ${{ secrets.GITHUB_TOKEN }}